# version: "3.8"

services:
  quiz-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"]
